# Generated by Django 3.2.9 on 2021-11-16 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211116_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='point',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.point', verbose_name='Номер аптеки'),
        ),
        migrations.AlterField(
            model_name='point',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Місто'),
        ),
    ]
