# Generated by Django 3.2.9 on 2021-11-16 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211116_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.point', verbose_name='Точка'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='pid',
            field=models.IntegerField(verbose_name='Номер аптеки'),
        ),
    ]
