# Generated by Django 3.2.9 on 2021-11-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211116_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='pid',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер аптеки'),
            preserve_default=False,
        ),
    ]
