# Generated by Django 3.2.9 on 2021-11-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_point_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='pid',
            field=models.CharField(max_length=15, verbose_name='Номер аптеки'),
        ),
    ]
