# Generated by Django 3.2.9 on 2021-11-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_point_pid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Місто', 'verbose_name_plural': 'Міста'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name'], 'verbose_name': 'Препарат', 'verbose_name_plural': 'Препарати'},
        ),
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['-pid'], 'verbose_name': 'Точка', 'verbose_name_plural': 'Точки'},
        ),
    ]
