# Generated by Django 3.2.9 on 2021-11-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211116_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['pid'], 'verbose_name': 'Точка', 'verbose_name_plural': 'Точки'},
        ),
        migrations.AlterField(
            model_name='point',
            name='pid',
            field=models.PositiveIntegerField(verbose_name='Номер аптеки'),
        ),
    ]
