# Generated by Django 3.2.9 on 2021-11-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211116_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='point',
            name='pid',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер аптеки'),
        ),
    ]
