# Generated by Django 3.2.9 on 2021-11-16 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211116_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'Препарат', 'verbose_name_plural': 'Препарати'},
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.point', verbose_name='Номер аптеки'),
            preserve_default=False,
        ),
    ]
