# Generated by Django 3.2.9 on 2021-11-16 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Назва')),
                ('qua', models.PositiveIntegerField(verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ціна')),
                ('code', models.PositiveIntegerField(verbose_name='Код')),
                ('manufacture', models.CharField(max_length=100, verbose_name='Мануфактура')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.point', verbose_name='Номер аптеки')),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Препарати',
            },
        ),
    ]
