# Generated by Django 3.2.9 on 2021-11-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_medicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
